version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10

  clickhouse01:
    image: redmagic039/clickhouse01:latest
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    depends_on:
      - zookeeper

  clickhouse02:
    image: redmagic039/clickhouse02:latest
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    depends_on:
      - zookeeper

  clickhouse03:
    image: redmagic039/clickhouse03:latest
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    depends_on:
      - zookeeper

  clickhouse04:
    image: redmagic039/clickhouse04:latest
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24